### ISSUE TITLE
Persistent Files. (Nexys4DDR)

### ISSUE THREAD

**Issue by samlarsen18** [litex-hub/linux-on-litex-vexriscv#53] opened 2019-10-23 20:26 UTC
I'm looking for a way to have persistent files booted up with linux. 

Is there a way to add files to the linux image that is loaded onto the board? With the sd not currently supported on the nexys4DDR is there another solution?

**Comment by mithro** [comment] 2019-10-25 01:24
I believe @kgugala might know some people working on trying to get LiteSDCard to work under Linux.

**Comment by enjoy-digital** [comment] 2020-07-20 20:55
This is a duplicate of #12, let's continue the discussion there.

**Closed by enjoy-digital** 2020-07-20 20:55 UTC
Labels: enhancement, question
